### ISSUE TITLE
Add support of Google Cloud Notifications

### ISSUE THREAD

**Issue by gen1us2k** [copybird/copybird#33]

**Comment by anatoliyfedorenko** [comment]
@0verIords are you still up to doing this task? 

@gen1us2k again more description needed. What exactly should happen? Are you talking about Firebase notifications? Push notifications? Cloud Pub/Sub Notifications for Cloud Storage? Not clear here :( Not sure what users would need to have to use this feature. Lets' think about it and update issue description
