### ISSUE TITLE
Add trigger support for mysql

### ISSUE THREAD

**Issue by gen1us2k** [copybird/copybird#66]

**Comment by anatoliyfedorenko** [comment]
Need to understand how to implement backups for mysql triggers

**Comment by anatoliyfedorenko** [comment]
Bad connection issue resolved. When I run mysql in docker and use ports 3306 for connection, I need to use `172.17.0.2` in connect DSN instead of `localhost` but now I need to figure out how to create the exact same database the test wants. @gen1us2k all these should be documented properly :(
