### ISSUE TITLE
Add support of AWS SQS for notifications

### ISSUE THREAD

**Issue by gen1us2k** [copybird/copybird#7]

**Comment by anatoliyfedorenko** [comment]
https://docs.aws.amazon.com/sdk-for-go/api/service/sqs/

**Comment by anatoliyfedorenko** [comment]
https://docs.aws.amazon.com/sdk-for-go/api/service/sqs/#New
https://docs.aws.amazon.com/sdk-for-go/api/service/sqs/#SQS.SendMessage
